знакомство с numpy

In [ ]:
import numpy as np

In [ ]:
# @title Одномерный массив
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

двумерный массив

In [ ]:
np.arange(20).reshape(4, 5)
# 5 - columns

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

трехмерный массив

In [ ]:
np.arange(12).reshape(3, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

превращение обычного списка в одномерный array массив

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

типы данных в массиве

тип int

In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int64)

тип float

In [ ]:
np.array([1, 2, 3, 4, 5], dtype=np.float64)

array([1., 2., 3., 4., 5.])

**Свойство массивов. Функции автозаполнения.**

---



In [ ]:
import numpy as np

In [ ]:
np_array = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])

количество осей

In [ ]:
np_array.ndim

2

число элементов

In [ ]:
np_array.size

9

число элементов по осям

In [ ]:
np_array.shape

(3, 3)

изменить форму по осям

In [ ]:
np_array.shape = 9, 1
np_array

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [3],
       [4],
       [5]])

получить тип данных

In [ ]:
np_array.dtype

dtype('int64')

изменить тип данных на новый

In [ ]:
np_array.dtype = np.int8
np_array

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 0, 0, 0],
       [5, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

одномерный массив с 7ю элементами с неопределенными значениями

In [ ]:
np.empty(7)

array([4.91256128e-310, 0.00000000e+000, 6.93745773e-310, 6.93745773e-310,
       2.37636758e-038, 1.00975163e-028, 7.11454530e-322])

In [ ]:
np.empty([3, 2, 1], dtype=np.int8)

array([[[  26],
        [-110]],

       [[  45],
        [ -86]],

       [[ 110],
        [  90]]], dtype=int8)

In [ ]:
np.ones([3, 3, 2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np_array = np.empty([3, 2, 2])
np_array

array([[[6.93666722e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

Массив со всеми нулями и такого же размера как и массив который в эту функцию передан.




In [ ]:
np.zeros_like(np_array)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

наполнение массива 7ками Массив заданного размера и типа данных заполненный переданным в функцию числом.

In [ ]:
np.full([3, 2, 3],7)

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

In [ ]:
np_array = np.empty([3, 2, 2])
np_array

array([[[4.91256258e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
np.full_like(np_array, 7, dtype = np.int32)

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]], dtype=int32)

массивы из числовых диапазонов

In [ ]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(7, 17)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
np.arange(7, 17, 3)

array([ 7, 10, 13, 16])

In [ ]:
np.arange(7, 10, 0.5)

array([7. , 7.5, 8. , 8.5, 9. , 9.5])

матрицы

Переданный список преобразует в матрицу.

In [ ]:
np.mat([1, 2, 3, 4, 5])

matrix([[1, 2, 3, 4, 5]])

In [ ]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Список преобразует в диагональную матрицу.

In [ ]:
np.diag(np_array)

array([1, 5, 9])

In [ ]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.diagflat(np_array)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

Вернет матрицу указанного размера с единицами на главной диагонали.

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Вернет нижнюю треугольную матрицу состоящую из единиц.

In [ ]:
np.tri(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.tril(np_array)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [ ]:
np.tril([7, 8, 9])

array([[7, 0, 0],
       [7, 8, 0],
       [7, 8, 9]])

Вернет верхнюю треугольную матрицу состоящую из элементов переданного в функцию массива.

In [ ]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.triu(np_array)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

**Представления массивов, изменение формы и создание копий.**

---



In [ ]:
import numpy as np

In [ ]:
np_array = np.array([[1, 2, 3, 3], [2, 3, 4, 5], [3, 4, 5, 6]])

In [ ]:
np_array.shape = 12
np_array

array([1, 2, 3, 3, 2, 3, 4, 5, 3, 4, 5, 6])

In [ ]:
np_array.shape = (2, 6)
np_array

array([[1, 2, 3, 3, 2, 3],
       [4, 5, 3, 4, 5, 6]])

In [ ]:
np_array.shape = (4, 3)
np_array

array([[1, 2, 3],
       [3, 2, 3],
       [4, 5, 3],
       [4, 5, 6]])

из 2х мерного в 3х мерный массив

In [ ]:
np_array.shape = (2, 2, 3)
np_array

array([[[1, 2, 3],
        [3, 2, 3]],

       [[4, 5, 3],
        [4, 5, 6]]])

In [ ]:
np_array.shape = (-1, 12)
np_array

array([[1, 2, 3, 3, 2, 3, 4, 5, 3, 4, 5, 6]])

In [ ]:
np_array.shape = (4, -1)
np_array

array([[1, 2, 3],
       [3, 2, 3],
       [4, 5, 3],
       [4, 5, 6]])

заполнение элементов в новом представлении

In [ ]:
np_array.shape = 4, 3
np_array

array([[1, 2, 3],
       [3, 2, 3],
       [4, 5, 3],
       [4, 5, 6]])

In [ ]:
np_array.shape = 3, 4
np_array

array([[1, 2, 3, 3],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

.reshape() создает новое представление того же массива

In [ ]:
np_array.reshape([2, 2, 3])
np_array

array([[1, 2, 3, 3],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [ ]:
new_array = np_array.reshape([2, 2, 3])
new_array

array([[[1, 2, 3],
        [3, 2, 3]],

       [[4, 5, 3],
        [4, 5, 6]]])

In [ ]:
new_array[0] = 100
new_array

array([[[100, 100, 100],
        [100, 100, 100]],

       [[  4,   5,   3],
        [  4,   5,   6]]])

In [ ]:
np_array

array([[100, 100, 100, 100],
       [100, 100,   4,   5],
       [  3,   4,   5,   6]])

resize() - меняет представление массива, но не сохраняет при этом изначальный размер

In [ ]:
np_array.resize((2, 6))
np_array

array([[100, 100, 100, 100, 100, 100],
       [  4,   5,   3,   4,   5,   6]])

In [ ]:
np_array.resize((4, 2), refcheck=False)
np_array

array([[100, 100],
       [100, 100],
       [100, 100],
       [  4,   5]])

представление любого массива в виде одномерного

In [ ]:
np_array.ravel()

array([100, 100, 100, 100, 100, 100,   4,   5])

копия представления массива

In [ ]:
np_array = np.array([[1, 2, 3, 3], [2, 3, 4, 5], [3, 4, 5, 6]])

In [ ]:
new_array = np_array.view()
np_array

array([[100, 100],
       [100, 100],
       [100, 100],
       [  4,   5]])

In [ ]:
new_array

array([[100, 100],
       [100, 100],
       [100, 100],
       [  4,   5]])

In [ ]:
np_array[0] = 7
np_array

array([[  7,   7],
       [100, 100],
       [100, 100],
       [  4,   5]])

In [ ]:
new_array

array([[  7,   7],
       [100, 100],
       [100, 100],
       [  4,   5]])

In [ ]:
np_array = np.array([[1, 2, 3, 3], [2, 3, 4, 5], [3, 4, 5, 6]])
np_array.shape = (2, 6)
np_array

array([[1, 2, 3, 3, 2, 3],
       [4, 5, 3, 4, 5, 6]])

In [ ]:
new_array

array([[  7,   7],
       [100, 100],
       [100, 100],
       [  4,   5]])

полная копия массива

In [ ]:
np_array = np.array([[1, 2, 3, 3], [2, 3, 4, 5], [3, 4, 5, 6]])
new_array = np_array.copy()
new_array

array([[1, 2, 3, 3, 2, 3],
       [4, 5, 3, 4, 5, 6]])

In [ ]:
np_array[0] = 3
np_array

array([[3, 3, 3, 3, 3, 3],
       [4, 5, 3, 4, 5, 6]])

In [ ]:
new_array

array([[1, 2, 3, 3, 2, 3],
       [4, 5, 3, 4, 5, 6]])

In [ ]:
np_array = np.array([[1, 2, 3, 3], [2, 3, 4, 5], [3, 4, 5, 6]])
np_array.shape = (2, 2, 3)
np_array

array([[[1, 2, 3],
        [3, 2, 3]],

       [[4, 5, 3],
        [4, 5, 6]]])

In [ ]:
new_array

array([[1, 2, 3, 3, 2, 3],
       [4, 5, 3, 4, 5, 6]])

**добавление осей. Объединение и разделение массивов.**

---



In [ ]:
import numpy as np

In [ ]:
np_array = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]])
np_array.shape

(3, 4)

In [ ]:
np_array

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

добавление осей.

In [ ]:
new_array = np.expand_dims(np_array, axis=0)
np_array.shape

(3, 4)

In [ ]:
new_array.shape

(1, 3, 4)

In [ ]:
new_array[0,0] = 100
np_array

array([[100, 100, 100, 100],
       [  2,   3,   4,   5],
       [  3,   4,   5,   6]])

In [ ]:
new_array

array([[[100, 100, 100, 100],
        [  2,   3,   4,   5],
        [  3,   4,   5,   6]]])

другой способ добавления осей. Добавление 0й оси.

In [ ]:
new_array = np_array[np.newaxis]
np_array.shape

(3, 4)

In [ ]:
new_array.shape

(1, 3, 4)

добавление 1й оси.

In [ ]:
new_array = np_array[:, np.newaxis]
np_array.shape

(3, 4)

In [ ]:
new_array.shape

(3, 1, 4)

добавление 0й и 2й осей.

In [ ]:
new_array = np_array[np.newaxis, : , np.newaxis]
np_array.shape

(3, 4)

In [ ]:
new_array.shape

(1, 3, 1, 4)

добавление последней оси.

In [ ]:
new_array = np_array[:, :, np.newaxis]
np_array.shape

(3, 4)

In [ ]:
new_array.shape

(3, 4, 1)

Другой вариант добавления последней оси.

In [ ]:
new_array = np_array[..., np.newaxis]
np_array

array([[100, 100, 100, 100],
       [  2,   3,   4,   5],
       [  3,   4,   5,   6]])

In [ ]:
new_array

array([[[100],
        [100],
        [100],
        [100]],

       [[  2],
        [  3],
        [  4],
        [  5]],

       [[  3],
        [  4],
        [  5],
        [  6]]])

добавление осей дает новое представление массива, если меняем значения в одном из массивов, оно также меняется и в другом:

In [ ]:
new_array[0, 0] = 77
np_array

array([[ 77, 100, 100, 100],
       [  2,   3,   4,   5],
       [  3,   4,   5,   6]])

In [ ]:
new_array

array([[[ 77],
        [100],
        [100],
        [100]],

       [[  2],
        [  3],
        [  4],
        [  5]],

       [[  3],
        [  4],
        [  5],
        [  6]]])

удаление осей. можно удалить только ось с одним элементом.

In [ ]:
new_array.shape

(3, 4, 1)

In [ ]:
new_array = np.squeeze(new_array)
new_array.shape

(3, 4)

объединение по 1й оси.

In [ ]:
arr_1 = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
arr_2 = np.array([[4, 5, 6], [5, 6, 7], [6, 7, 8]])
arr_3 = np.array([[7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12]])
arr_1.shape

(3, 3)

In [ ]:
arr_1

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
arr_2.shape

(3, 3)

In [ ]:
arr_2

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [ ]:
arr_3.shape

(3, 4)

In [ ]:
arr_3

array([[ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12]])

массивы должны иметь одинаковый размер вдоль всех осей, кроме 1й оси.

In [ ]:
new_arr = np.hstack([arr_1, arr_2, arr_3])
new_arr.shape

(3, 10)

In [ ]:
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

пример использования с объединением осей:

In [ ]:
arr_1 = np.empty([27, 8, 3])
arr_2 = np.empty([27, 10, 3])
arr_3 = np.empty([27, 9, 3])
arr_1.shape

(27, 8, 3)

In [ ]:
arr_2.shape

(27, 10, 3)

In [ ]:
arr_3.shape

(27, 9, 3)

.hstack() - объединение массивов по отличающейся оси:

In [ ]:
new_arr = np.hstack([arr_1, arr_2, arr_3])
new_arr.shape

(27, 27, 3)

объединение по нулевой оси.

In [ ]:
arr_1 = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
arr_2 = np.array([[4, 5, 6], [5, 6, 7], [6, 7, 8]])
arr_3 = np.array([[7, 8, 9], [8, 9, 10], [9, 10, 11], [10, 11, 12]])
arr_1.shape

(3, 3)

In [ ]:
arr_1

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
arr_2.shape

(3, 3)

In [ ]:
arr_2

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [ ]:
arr_3.shape

(4, 3)

In [ ]:
arr_3

array([[ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12]])

количество элементов во всех массивах кроме 0й оси по всем осям должно быть одинаковым.

In [ ]:
new_arr = np.vstack([arr_1, arr_2, arr_3])
new_arr.shape

(10, 3)

In [ ]:
new_arr

пример применения:

In [ ]:
arr_1 = np.empty([9, 27, 3])
arr_2 = np.empty([10, 27, 3])
arr_3 = np.empty([8, 27, 3])
arr_1.shape

(9, 27, 3)

In [ ]:
arr_2.shape

(10, 27, 3)

In [ ]:
arr_3.shape

(8, 27, 3)

In [ ]:
new_arr = np.vstack([arr_1, arr_2, arr_3])
new_arr.shape

(27, 27, 3)

конкатенация. объединение по указанной оси.

In [ ]:
arr_1 = np.empty([27, 27, 1])
arr_2 = np.empty([27, 27, 1])
arr_3 = np.empty([27, 27, 1])
arr_1.shape

(27, 27, 1)

In [ ]:
arr_2.shape

(27, 27, 1)

In [ ]:
arr_3.shape

(27, 27, 1)

количество элементов по всем осям, кроме оси, по которой идет объединение, должно быть одинаковым:

In [ ]:
new_arr = np.concatenate([arr_1, arr_2, arr_3], axis=2)
new_arr.shape

(27, 27, 3)

разделение массивов.

In [ ]:
arr_1 = np.array([['x_1', 'y_1'], ['x_2', 'y_2'], ['x_3', 'y_3'], ['x_4', 'y_4']])
arr_1.shape

(4, 2)

In [ ]:
arr_1

array([['x_1', 'y_1'],
       ['x_2', 'y_2'],
       ['x_3', 'y_3'],
       ['x_4', 'y_4']], dtype='<U3')

In [ ]:
arr_list = np.array_split(arr_1, 4, axis=0) # 4 - сколько частей
arr_list

[array([['x_1', 'y_1']], dtype='<U3'),
 array([['x_2', 'y_2']], dtype='<U3'),
 array([['x_3', 'y_3']], dtype='<U3'),
 array([['x_4', 'y_4']], dtype='<U3')]

split() возвращает новое представление данного массива -> если в данных массивах поменять значения -> значения поменяются и в исходном массиве:

In [ ]:
arr_list[0][0] = 1
arr_1

array([['1', '1'],
       ['x_2', 'y_2'],
       ['x_3', 'y_3'],
       ['x_4', 'y_4']], dtype='<U3')

**добавление и удаление элементов в массив.**

---



добавление элементов в массив.

In [ ]:
import numpy as np

In [ ]:
data = np.empty([1000, 28, 28])
arr_1 = np.empty([50, 28, 28])
arr_2 = np.empty([28, 28])
data.shape

(1000, 28, 28)

In [ ]:
arr_1.shape

(50, 28, 28)

In [ ]:
arr_2.shape

(28, 28)

In [ ]:
new_data = np.append(data, arr_1)  # вернет одномерный массив

append() создаст копию массива data с добавленными элементами из arr_1

In [ ]:
new_data.shape

(823200,)

In [ ]:
new_data = np.append(data, arr_1, axis=0)
new_data.shape

(1050, 28, 28)

In [ ]:
new_data = np.append(data, arr_2[np.newaxis], axis=0)
new_data.shape

(1001, 28, 28)

удаление элементов.

In [ ]:
new_data = np.delete(new_data, 1000, axis=0)
new_data.shape

(1000, 28, 28)

ускорить добавление элементов в массив.

пример медленной работы.

In [ ]:
%%time
arr_1 = np.empty([1000, 28, 28])
for i in range(1000):
  img = np.random.randint(0, 255, 28 * 28).reshape([28, 28])
  arr_1 = np.append(arr_1, img[np.newaxis], axis=0)

CPU times: user 1.41 s, sys: 3.42 s, total: 4.82 s
Wall time: 4.85 s


пример с ускорением добавления элементов в массив. Не добавляем элементы, а меняем старые. Используется, когда нужно добавить много элементов.

In [ ]:
%%time
arr = np.empty([1000, 28, 28])
arr.resize([2000, 28, 28])
for i in range(1000):
  img = np.random.randint(0, 255, 28 * 28).reshape([28, 28])
  arr[1000 + i] = img

CPU times: user 23.1 ms, sys: 6.05 ms, total: 29.2 ms
Wall time: 30.2 ms


При удалении элементов с помощью функции np.delete() можно:

передавать индекс элемента который нужно удалить
          np.delete(..., 5, axis=...)

передавать список или массив с индексами элементов которые нужно удалить
          np.delete(..., [2, 4, 19], axis=...)

передавать список или массив с булевыми значениями. Количество элементов в списке\массиве с булевыми значениями должно совпадать с количеством элементов оси на которой удаляются элементы. Будут удалены элементы чей индекс равен индексам значений True.
          np.delete(..., [True, False, False], axis=...)

**индексация и срезы.**

---



In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[3]

4

если массив не одномерный.

In [ ]:
arr = np.arange(18).reshape(3, 3, 2)
arr.shape

(3, 3, 2)

In [ ]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [ ]:
arr[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr[2, 0]

array([12, 13])

In [ ]:
arr[2, 2, 0]

16

меняем элементы массива.

In [ ]:
arr[1, 2] = [100, 100]
arr

array([[[  0,   1],
        [  2,   3],
        [  4,   5]],

       [[  6,   7],
        [  8,   9],
        [100, 100]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]]])

In [ ]:
arr = np.arange(18).reshape(3, 3, 2)
arr[0, 0, 1] = 7
arr

array([[[ 0,  7],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

срезы.

In [ ]:
arr = np.arange(4*3*2).reshape([4, 3, 2])
arr.shape

(4, 3, 2)

In [ ]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
arr[0: 2, 2] # срезы возвращают новое представление массива.

array([[ 4,  5],
       [10, 11]])

полный срез элементов для любой из осей:

In [ ]:
arr[:, 1]

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]])

In [ ]:
arr[1:, :, 1]

array([[ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [ ]:
arr[::2, 2]

array([[ 4,  5],
       [16, 17]])

поменять элементы массива:

In [ ]:
arr

array([[[100, 100],
        [100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100],
        [100, 100]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

In [ ]:
arr[:2] = 100
arr

array([[[100, 100],
        [100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100],
        [100, 100]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

In [ ]:
new_arr = arr[:, 1]
new_arr

array([[100, 100],
       [100, 100],
       [ 14,  15],
       [ 20,  21]])

In [ ]:
arr

array([[[100, 100],
        [100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100],
        [100, 100]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

In [ ]:
new_arr[1] = 50
new_arr

array([[100, 100],
       [ 50,  50],
       [ 14,  15],
       [ 20,  21]])

In [ ]:
arr

array([[[100, 100],
        [100, 100],
        [100, 100]],

       [[100, 100],
        [ 50,  50],
        [100, 100]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

срезы возвращают новое представление массивов, изменения касаются исходного массива.

списочная индексация.

In [ ]:
arr[[1, 3, 1, 2, 0]]

array([[[100, 100],
        [ 50,  50],
        [100, 100]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]],

       [[100, 100],
        [ 50,  50],
        [100, 100]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]],

       [[100, 100],
        [100, 100],
        [100, 100]]])

In [ ]:
arr[np.array([1, 3, 1, 2, 0])]

array([[[100, 100],
        [ 50,  50],
        [100, 100]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]],

       [[100, 100],
        [ 50,  50],
        [100, 100]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]],

       [[100, 100],
        [100, 100],
        [100, 100]]])

In [ ]:
arr[[True, False, False, True]] # количество элементов должно совпадать с количеством элементов на нулевой оси.

array([[[100, 100],
        [100, 100],
        [100, 100]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

In [ ]:
new_arr = arr[[True, False, False, True]]
new_arr

array([[[100, 100],
        [100, 100],
        [100, 100]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

In [ ]:
new_arr[0, 1] = 200
new_arr

array([[[100, 100],
        [200, 200],
        [100, 100]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

In [ ]:
arr

array([[[100, 100],
        [100, 100],
        [100, 100]],

       [[100, 100],
        [ 50,  50],
        [100, 100]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

при списчной индексации возвращается копия массива. Изменения не касаются исходного массива.

In [ ]:
arr = np.arange(6).reshape([3, 2])
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
index = np.array([[0, 0, 1], [1, 0, 2]])
index

array([[0, 0, 1],
       [1, 0, 2]])

In [ ]:
arr[index]

array([[[0, 1],
        [0, 1],
        [2, 3]],

       [[2, 3],
        [0, 1],
        [4, 5]]])

**математические операции. транслирование массивов.**

---



In [ ]:
import numpy as np

In [ ]:
arr_1 = np.arange(6).reshape(3, 2)
arr_1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr_2 = np.arange(10, 16).reshape(3, 2)
arr_2

array([[10, 11],
       [12, 13],
       [14, 15]])

простые математические операции с числами.

In [ ]:
arr_1 + 5

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

математические операции с массивами одинакового размера.

In [ ]:
arr_1 + arr_2

array([[10, 12],
       [14, 16],
       [18, 20]])

математические операции с массивами разного размера.

In [ ]:
arr = np.array([3])
arr.shape

(1,)

In [ ]:
arr

array([3])

In [ ]:
arr_1.shape

(3, 2)

In [ ]:
arr_1 * arr

array([[ 0,  3],
       [ 6,  9],
       [12, 15]])

транслирование массивов.
согласованные массивы - массивы одинакового размера. математические операции и операции сравнения можно проводить только с массивами согласованными. Если массивы не согласованы, то выполняется транслирование, тогда математические операции и операции сравнения становятся возможными.
Правила транслирования:
1. если массивы имеют разное количество осей, то к массиву с меньшим количеством, добавляются новые, чтобы размерности совпали. Автоматически добавление осей происходит слева, но самим можно добавлять любые оси.
2. в массивах на соответствующих осях должно быть одинаковое количество элементов, или 1 элемент в одном из массивов.
Массив любого размера всегда согласован с числом или с массивом, состоящим из одного элемента.

In [107]:
arr = np.array([5, 2, 7])
arr.shape

(3,)

In [108]:
arr_1.shape

(3, 2)

In [109]:
arr_1 * arr

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [111]:
arr = np.arange(3).reshape([1, 3])
arr

array([[0, 1, 2]])

In [112]:
arr_1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [113]:
arr.shape

(1, 3)

In [114]:
arr_1.shape

(3, 2)

In [115]:
arr.shape = [3, 1]
arr.shape

(3, 1)

In [116]:
arr_1.shape

(3, 2)

In [117]:
arr_1 + arr

array([[0, 1],
       [3, 4],
       [6, 7]])

In [119]:
arr = np.arange(4 * 3 * 2).reshape([4, 3, 2])
arr.shape

(4, 3, 2)

In [120]:
arr_1 = np.arange(4 * 2).reshape([4, 2])
arr_1.shape

(4, 2)

In [121]:
arr_1.shape = (4, 1, 2)
arr_1.shape

(4, 1, 2)

In [122]:
arr.shape

(4, 3, 2)

In [123]:
arr * arr_1

array([[[  0,   1],
        [  0,   3],
        [  0,   5]],

       [[ 12,  21],
        [ 16,  27],
        [ 20,  33]],

       [[ 48,  65],
        [ 56,  75],
        [ 64,  85]],

       [[108, 133],
        [120, 147],
        [132, 161]]])

In [124]:
arr = np.arange(5 * 3 * 2).reshape([5, 3, 2])
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [125]:
arr_1 = np.arange(5, 10)
arr_1

array([5, 6, 7, 8, 9])

In [127]:
arr_1.shape = (5, 1, 1)
arr_1.shape

(5, 1, 1)

In [128]:
arr.shape

(5, 3, 2)

In [129]:
arr - arr_1

array([[[-5, -4],
        [-3, -2],
        [-1,  0]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[10, 11],
        [12, 13],
        [14, 15]],

       [[15, 16],
        [17, 18],
        [19, 20]]])

**математические функции.**

---



In [1]:
import numpy as np

In [2]:
arr = np.arange(2, 20).reshape([3, 3, 2])
arr

array([[[ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19]]])

In [4]:
arr.min()

2

In [5]:
arr.max()

19

In [6]:
arr.sum()

189

In [7]:
arr.mean()

10.5

In [8]:
np.abs(np.array([[-1, 2, 3], [-2, 1, 3]]))

array([[1, 2, 3],
       [2, 1, 3]])

In [9]:
np.max(arr)

19

In [10]:
np.log(arr)

array([[[0.69314718, 1.09861229],
        [1.38629436, 1.60943791],
        [1.79175947, 1.94591015]],

       [[2.07944154, 2.19722458],
        [2.30258509, 2.39789527],
        [2.48490665, 2.56494936]],

       [[2.63905733, 2.7080502 ],
        [2.77258872, 2.83321334],
        [2.89037176, 2.94443898]]])

In [11]:
np.exp(arr)

array([[[7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02],
        [4.03428793e+02, 1.09663316e+03]],

       [[2.98095799e+03, 8.10308393e+03],
        [2.20264658e+04, 5.98741417e+04],
        [1.62754791e+05, 4.42413392e+05]],

       [[1.20260428e+06, 3.26901737e+06],
        [8.88611052e+06, 2.41549528e+07],
        [6.56599691e+07, 1.78482301e+08]]])

In [12]:
np.log(np.exp(arr))

array([[[ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.]],

       [[14., 15.],
        [16., 17.],
        [18., 19.]]])

тригонометрические функции.

In [13]:
np.sin(arr)

array([[[ 0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427],
        [-0.2794155 ,  0.6569866 ]],

       [[ 0.98935825,  0.41211849],
        [-0.54402111, -0.99999021],
        [-0.53657292,  0.42016704]],

       [[ 0.99060736,  0.65028784],
        [-0.28790332, -0.96139749],
        [-0.75098725,  0.14987721]]])

In [14]:
np.cos(arr)

array([[[-0.41614684, -0.9899925 ],
        [-0.65364362,  0.28366219],
        [ 0.96017029,  0.75390225]],

       [[-0.14550003, -0.91113026],
        [-0.83907153,  0.0044257 ],
        [ 0.84385396,  0.90744678]],

       [[ 0.13673722, -0.75968791],
        [-0.95765948, -0.27516334],
        [ 0.66031671,  0.98870462]]])

In [15]:
np.arctan(arr)

array([[[1.10714872, 1.24904577],
        [1.32581766, 1.37340077],
        [1.40564765, 1.42889927]],

       [[1.44644133, 1.46013911],
        [1.47112767, 1.48013644],
        [1.48765509, 1.49402444]],

       [[1.49948886, 1.50422816],
        [1.50837752, 1.5120405 ],
        [1.51529782, 1.51821327]]])

применение функций по осям.

In [16]:
arr.shape

(3, 3, 2)

In [17]:
arr

array([[[ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19]]])

In [18]:
np.sum(arr, axis=0)

array([[24, 27],
       [30, 33],
       [36, 39]])

In [19]:
np.mean(arr, axis=1)

array([[ 4.,  5.],
       [10., 11.],
       [16., 17.]])

In [20]:
np.max(arr, axis=2)

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [21]:
arr = np.arange(10).reshape([5, 2])
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
arr = np.arange(18).reshape([3, 3, 2])
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [23]:
arr.shape = -1, 2
arr.shape

(9, 2)

In [25]:
arr = np.arange(3 * 4 * 4 * 3).reshape([3, 4, 4, 3])
arr

array([[[[  0,   1,   2],
         [  3,   4,   5],
         [  6,   7,   8],
         [  9,  10,  11]],

        [[ 12,  13,  14],
         [ 15,  16,  17],
         [ 18,  19,  20],
         [ 21,  22,  23]],

        [[ 24,  25,  26],
         [ 27,  28,  29],
         [ 30,  31,  32],
         [ 33,  34,  35]],

        [[ 36,  37,  38],
         [ 39,  40,  41],
         [ 42,  43,  44],
         [ 45,  46,  47]]],


       [[[ 48,  49,  50],
         [ 51,  52,  53],
         [ 54,  55,  56],
         [ 57,  58,  59]],

        [[ 60,  61,  62],
         [ 63,  64,  65],
         [ 66,  67,  68],
         [ 69,  70,  71]],

        [[ 72,  73,  74],
         [ 75,  76,  77],
         [ 78,  79,  80],
         [ 81,  82,  83]],

        [[ 84,  85,  86],
         [ 87,  88,  89],
         [ 90,  91,  92],
         [ 93,  94,  95]]],


       [[[ 96,  97,  98],
         [ 99, 100, 101],
         [102, 103, 104],
         [105, 106, 107]],

        [[108, 109, 110],
         [111, 1

In [26]:
arr.shape = [3, 4 * 4, 3]
arr.shape

(3, 16, 3)

In [27]:
arr.shape = -1, 3
arr.shape

(48, 3)

In [28]:
np.mean(arr, axis=0)

array([70.5, 71.5, 72.5])

статистические функции.

In [29]:
np.median(arr)

71.5

In [30]:
np.var(arr) # дисперсия

1727.9166666666667

In [31]:
np.std(arr)  # стандартное отклонение

41.56821702535083

генерации псевдослучайных чисел. модуль random.

In [32]:
np.random.rand() # массив заданной формы, равномерного распределения [0, 1)

0.13205712769284728

In [33]:
np.random.rand(4)

array([0.88370019, 0.84814537, 0.33469272, 0.31678485])

In [34]:
np.random.rand(3, 2)

array([[0.0144721 , 0.44042112],
       [0.00260766, 0.58861606],
       [0.93058707, 0.09842231]])

In [35]:
np.random.randn() # стандартное нормальное отклонение

-0.8717834547871198

In [36]:
np.random.randn(6)

array([ 0.78940793, -0.42045347,  0.18736745,  0.19375751,  0.34431374,
       -0.84980141])

In [37]:
np.random.randn(4, 3)

array([[-0.82359333,  0.377968  , -0.18652086],
       [-0.74483085,  0.39734929, -1.35390645],
       [-0.54661128,  1.27476908,  0.16109466],
       [-0.37311463, -1.24306818,  0.28265988]])

In [39]:
np.random.normal(5, 10) # нормальное распределение

-4.43098577140767

In [38]:
np.random.normal(5, 10, 100)

array([ 13.71434662,   4.21764623,   4.61786559,   7.92802228,
         1.86165206,   7.88522747,  -7.98074101,  12.40095161,
        -8.76071382,  17.25663455,  20.18480815,   4.73506867,
         0.67736925,  20.59546348,   4.74589258,  19.88836705,
         0.03755092,   9.00453733,   8.48286663,   9.87530567,
         2.82044756,  11.01668352,   5.11961651,  19.0080875 ,
        25.4844617 ,  11.67961256,  -8.56263459,  11.57701753,
        13.58318735,   2.78821681,   6.06256065,   7.73282282,
       -20.38407305,   6.87822953,  -3.28741968, -12.36678041,
        23.61423775, -14.04307281,  14.24275002,  18.21678501,
         6.73668421,  -0.92875593,  12.97695752,  -4.23225427,
         7.83119613,   9.8258029 ,  -6.89916396,  12.54965295,
        -9.63735077,   4.92776263,   6.7439213 ,  19.79861194,
        -0.41053452,  -0.47431983,   8.74403364,   7.72206383,
         6.24724763,   6.09917037, -10.74311093,  -5.71332109,
        18.71908362,  18.04573551,  -1.79410709,  27.43

In [40]:
np.random.normal(5, 10, [4, 2])

array([[10.97015541,  9.34799073],
       [-3.91789106, 15.77594914],
       [-2.70697219, -0.59935878],
       [12.30230225, 14.49031384]])

In [41]:
np.random.randint(5) # целые числа из дискретного равномерного распределения

2

In [42]:
np.random.randint(4, 10)

6

In [43]:
np.random.randint(4, 20, size=(4, 2))

array([[15, 14],
       [17,  6],
       [16, 11],
       [ 7, 17]])

In [44]:
np.random.choice([1, 2, 3, 4, 5], 10)

array([5, 2, 5, 5, 5, 5, 1, 4, 2, 5])

In [45]:
np.random.shuffle(arr) # перемешиваем массив вдоль нулевой оси.
arr

array([[ 60,  61,  62],
       [ 33,  34,  35],
       [ 42,  43,  44],
       [ 27,  28,  29],
       [ 39,  40,  41],
       [ 90,  91,  92],
       [ 66,  67,  68],
       [ 72,  73,  74],
       [ 30,  31,  32],
       [  9,  10,  11],
       [123, 124, 125],
       [ 18,  19,  20],
       [ 75,  76,  77],
       [ 87,  88,  89],
       [ 63,  64,  65],
       [132, 133, 134],
       [  3,   4,   5],
       [ 12,  13,  14],
       [ 21,  22,  23],
       [ 15,  16,  17],
       [138, 139, 140],
       [ 24,  25,  26],
       [ 99, 100, 101],
       [ 36,  37,  38],
       [ 54,  55,  56],
       [ 69,  70,  71],
       [129, 130, 131],
       [126, 127, 128],
       [111, 112, 113],
       [105, 106, 107],
       [ 57,  58,  59],
       [ 84,  85,  86],
       [114, 115, 116],
       [ 81,  82,  83],
       [  0,   1,   2],
       [120, 121, 122],
       [117, 118, 119],
       [102, 103, 104],
       [ 45,  46,  47],
       [ 48,  49,  50],
       [ 78,  79,  80],
       [ 93,  94

In [50]:
np.random.seed(42)
np.random.randn(3, 2)

array([[ 0.49671415, -0.1382643 ],
       [ 0.64768854,  1.52302986],
       [-0.23415337, -0.23413696]])

In [53]:
np.random.randn(3, 2)

array([[-0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ],
       [ 0.0675282 , -1.42474819]])

**операции сравнения.**

---



In [1]:
import numpy as np

In [2]:
np.random.seed(42)
arr_1 = np.random.randint(10, size=[4, 3])
arr_2 = arr_1[[2, 1, 2, 0]]

In [3]:
arr_1

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7]])

In [4]:
arr_2

array([[2, 6, 7],
       [4, 6, 9],
       [2, 6, 7],
       [6, 3, 7]])

операции сравнения с числами.

In [5]:
arr_1 == 4

array([[False, False, False],
       [ True, False, False],
       [False, False, False],
       [ True, False, False]])

In [6]:
arr_1 <= 3

array([[False,  True, False],
       [False, False, False],
       [ True, False, False],
       [False,  True, False]])

In [7]:
arr_1 > 5

array([[ True, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [8]:
arr_1[arr_1 > 4] # получим элементы массива, которые больше 4х

array([6, 7, 6, 9, 6, 7, 7])

операции сравнения с массивами одинакового размера.

In [9]:
arr_1

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7]])

In [10]:
arr_2

array([[2, 6, 7],
       [4, 6, 9],
       [2, 6, 7],
       [6, 3, 7]])

In [11]:
arr_1 == arr_2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [12]:
arr_2 < arr_1

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [13]:
arr_1 != arr_2

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

сравнение согласованных массивов.

In [14]:
np.random.seed(42)
arr_3 = np.random.randint(10, size=[2, 3, 2])
shape_3_2 = np.arange(2, 8).reshape([3, 2])

In [15]:
arr_3

array([[[6, 3],
        [7, 4],
        [6, 9]],

       [[2, 6],
        [7, 4],
        [3, 7]]])

In [16]:
shape_3_2

array([[2, 3],
       [4, 5],
       [6, 7]])

In [17]:
arr_3 = [7, 3]

In [19]:
arr_3

[7, 3]

In [18]:
arr_3 > shape_3_2

array([[ True, False],
       [ True, False],
       [ True, False]])

функции для сравнения массивов:
np.greater()  >
np.greater_equal()  >=
np.less()  <
np.less_equal()  <=
np.equal()  ==
np.not_equal()  !=

In [20]:
np.random.seed(42)
arr_3 = np.random.randint(10, size=[2, 3, 2])
shape_3_2 = np.arange(2, 8).reshape([3, 2])

In [21]:
arr_3

array([[[6, 3],
        [7, 4],
        [6, 9]],

       [[2, 6],
        [7, 4],
        [3, 7]]])

In [22]:
shape_3_2

array([[2, 3],
       [4, 5],
       [6, 7]])

In [23]:
np.not_equal(arr_3, [2, 3])

array([[[ True, False],
        [ True,  True],
        [ True,  True]],

       [[False,  True],
        [ True,  True],
        [ True,  True]]])

In [24]:
np.less(arr_3, shape_3_2)

array([[[False, False],
        [False,  True],
        [False, False]],

       [[False, False],
        [False,  True],
        [ True, False]]])

проверка массивов на равенство.

In [25]:
arr_1

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7]])

In [26]:
arr_2

array([[2, 6, 7],
       [4, 6, 9],
       [2, 6, 7],
       [6, 3, 7]])

In [27]:
np.array_equal(arr_1, arr_2)

False

сравнение не согласованных массивов.

In [28]:
np.random.seed(42)
arr_3 = np.random.randint(10, size= [2, 3, 2])
shape_2_3 = np.arange(4, 10).reshape([2, 3])
shape_2 = np.array([6, 7])

In [29]:
arr_3

array([[[6, 3],
        [7, 4],
        [6, 9]],

       [[2, 6],
        [7, 4],
        [3, 7]]])

In [30]:
shape_2_3

array([[4, 5, 6],
       [7, 8, 9]])

In [31]:
shape_2

array([6, 7])

In [32]:
arr_3 == shape_2_3.reshape([2, 3, 1])

array([[[False, False],
        [False, False],
        [ True, False]],

       [[False, False],
        [False, False],
        [False, False]]])

In [33]:
arr_3 < shape_2

array([[[False,  True],
        [False,  True],
        [False, False]],

       [[ True,  True],
        [False,  True],
        [ True, False]]])

In [34]:
arr_3 < shape_2[:, np.newaxis, np.newaxis]

array([[[False,  True],
        [False,  True],
        [False, False]],

       [[ True,  True],
        [False,  True],
        [ True, False]]])

функции all и any.

In [35]:
arr = np.array([1, 2, 3, 4, 5])

In [36]:
arr < 5

array([ True,  True,  True,  True, False])

In [37]:
np.all(arr < 5)

False

In [38]:
arr < 2

array([ True, False, False, False, False])

In [39]:
np.any(arr < 2)

True

**матрицы и вектора.**

---



In [40]:
import numpy as np

In [41]:
np.random.seed(42)
vector_1 = np.array([1, 2, 3, 4, 5])
vector_2 = np.array([2, 3, 4, 5, 6 ])
matrix_1 = np.random.randint(10, size=[3, 3])
matrix_2 = np.random.randint(10, size=[3, 3])

In [42]:
vector_1

array([1, 2, 3, 4, 5])

In [43]:
vector_2

array([2, 3, 4, 5, 6])

In [44]:
matrix_1

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7]])

In [45]:
matrix_2

array([[4, 3, 7],
       [7, 2, 5],
       [4, 1, 7]])

умножение векторов. скалярное произведение.

In [46]:
np.dot(vector_1, vector_2) # 1 способ

70

In [49]:
vector_1 @ vector_2  # 2 способ

70

In [48]:
np.inner(vector_1, vector_2)   # 3 способ

70

внешнее произведение.

In [50]:
np.outer(vector_1, vector_2)

array([[ 2,  3,  4,  5,  6],
       [ 4,  6,  8, 10, 12],
       [ 6,  9, 12, 15, 18],
       [ 8, 12, 16, 20, 24],
       [10, 15, 20, 25, 30]])

умножение матриц.

In [51]:
np.dot(matrix_1, matrix_2) # 1 способ

array([[ 73,  31, 106],
       [ 94,  33, 121],
       [ 78,  25,  93]])

In [52]:
np.matmul(matrix_1, matrix_2)  # 2 способ

array([[ 73,  31, 106],
       [ 94,  33, 121],
       [ 78,  25,  93]])

In [53]:
matrix_1 @ matrix_2  # 3 способ

array([[ 73,  31, 106],
       [ 94,  33, 121],
       [ 78,  25,  93]])

умножение матриц с векторами.

In [54]:
np.random.seed(42)
vec_1 = np.array([1, 2, 3])
vec_2 = np.array([2, 3, 4, 5])
mat = np.random.randint(10, size=[4, 3])

In [55]:
vec_1

array([1, 2, 3])

In [56]:
vec_2

array([2, 3, 4, 5])

In [57]:
mat

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7]])

In [58]:
np.dot(vec_2, mat)  # 1 способ

array([ 52,  63, 104])

In [59]:
vec_2 @ mat   # 2 способ

array([ 52,  63, 104])

In [60]:
np.dot(mat, vec_1)  # 1 способ

array([33, 43, 35, 31])

In [61]:
mat @ vec_1   # 2 способ

array([33, 43, 35, 31])

In [62]:
vec_1[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [63]:
mat @ vec_1

array([33, 43, 35, 31])

In [64]:
mat @ vec_1[:, np.newaxis]

array([[33],
       [43],
       [35],
       [31]])

элементы линейной алгебры.

In [65]:
mat

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7]])

In [66]:
np.linalg.matrix_rank(mat)  # ранг матрицы

3

In [67]:
np.trace(mat)  # след матрицы

19

In [68]:
np.linalg.det(mat[:3])  # определитель матрицы

-17.999999999999982

In [69]:
np.linalg.eig(mat[:3])  # собственные значения и собственные вектора матрицы

EigResult(eigenvalues=array([16.51140818,  2.86861967, -0.38002785]), eigenvectors=array([[-0.5387936 , -0.91751959, -0.39475616],
       [-0.65676705,  0.03294597, -0.65762723],
       [-0.5275969 ,  0.39632355,  0.64163385]]))

In [70]:
np.linalg.inv(mat[:3])  # обратная матрица

array([[ 0.66666667, -1.16666667,  0.83333333],
       [ 0.55555556, -1.55555556,  1.44444444],
       [-0.66666667,  1.66666667, -1.33333333]])

In [71]:
np.linalg.svd(mat)  # сингулярное разложение

SVDResult(U=array([[-0.48238838,  0.67508291, -0.54741187,  0.10910895],
       [-0.59357851, -0.24369715,  0.07030585, -0.76376262],
       [-0.47059808, -0.64033725, -0.26624538,  0.54554473],
       [-0.43989027,  0.27357443,  0.79025991,  0.32732684]]), S=array([19.36614032,  3.7937295 ,  0.74848217]), Vh=array([[-0.41151212, -0.47257199, -0.77931604],
       [ 0.76160729, -0.64797304, -0.00923466],
       [-0.50061174, -0.59733295,  0.62656304]]))